<?php use Snowdog\Academy\Model\Book;

require_once(__DIR__ . '/../../common/header.phtml');

$action = '/admin/new_book';
if ($this->book instanceof Book) {
    $title = $this->book->getTitle();
    $author = $this->book->getAuthor();
    $isbn = $this->book->getIsbn();
    $action = '/admin/edit_book/' . $this->book->getId();
}
?>

<section id="new-book-form" class="padded">
    <form class="form-horizontal" method="POST" action="<?= $action ?>">
        <div class="form-group">
            <label for="book-title" class="col-sm-1 control-label">Title:</label>
            <div class="col-sm-10">
                <input type="text" id="book-title" name="title" class="form-control" value="<?= $title ?? ''?>" required/>
            </div>
        </div>
        <div class="form-group">
            <label for="author" class="col-sm-1 control-label">Author:</label>
            <div class="col-sm-10">
                <input type="text" id="author" name="author" class="form-control" value="<?= $author ?? ''?>" required/>
            </div>
        </div>
        <div class="form-group">
            <label for="isbn" class="col-sm-1 control-label">ISBN:</label>
            <div class="col-sm-10">
                <input type="text" id="isbn" name="isbn" class="form-control" value="<?= $isbn ?? ''?>" required/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-1 col-sm-2">
                <button type="submit" class="btn btn-primary">Save book</button>
            </div>
        </div>
    </form>
</section>
<section>
<a id="callAPi" class="btn btn-primary" onclick="CallApi()" disabled>Call Api</a>
</section>

<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script>

function CallApi() {
    var isbn = document.getElementById("isbn").value;
  
        fetch('https://www.googleapis.com/books/v1/volumes?q=isbn:'+isbn)
  .then(response => response.json())
  .then(data => {
    // console.log(data)
    var kinds=data.items;
     var volumeInfo=kinds[0].volumeInfo
    //  console.log(volumeInfo)
     var title=volumeInfo.title;
    //  console.log(title)
               var author=volumeInfo.authors[0];
            //    console.log(author)
               document.getElementById('book-title').value = title;
               document.getElementById('author').value = author;

      })
      .catch((error) => {
 alert("Enter Valid ISBN")
});

}
$( "#isbn" ).on('change',function() {
    $("#callAPi").attr("disabled",false);
});


</script>
<?php require_once(__DIR__ . '/../../common/footer.phtml'); ?>
