<?php use Snowdog\Academy\Model\Book;

require_once(__DIR__ . '/../../common/header.phtml'); ?>

<section id="add" class="padded">
    <a href="/admin/new_book" class="btn btn-primary">Add new book</a>
</section>  
<input type="file" id="fileUpload" />
<input type="button" id="upload" value="Upload" />
<hr />

<section id="book-list" class="padded">
    <h3>Book list</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Author</th>
                <th>ISBN</th>
                <th>Borrowed</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->getBooks() as $book): /** @var Book $book */?>
            <tr>
                <td><?= $book->getId()?></td>
                <td><?= $book->getTitle()?></td>
                <td><?= $book->getAuthor()?></td>
                <td><?= $book->getIsbn()?></td>
                <td><?= $book->isBorrowed() ? 'Yes' : 'No' ?></td>
                <td><a href="/admin/edit_book/<?=$book->getId()?>">Edit</a></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</section>
<section id="book-list" class="padded">
    <h3>Books being borrowed for more than X days</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Author</th>
                <th>ISBN</th>
                <th>Borrowed</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->getBooks() as $book): /** @var Book $book */?>
            <tr>
                <?php if ($book->isBorrowed() == 'Yes') :?>
                <td><?= $book->getId()?></td>
                <td><?= $book->getTitle()?></td>
                <td><?= $book->getAuthor()?></td>
                <td><?= $book->getIsbn()?></td>
                <td><?= $book->isBorrowed() ? 'Yes' : 'No' ?></td>
                <td><a href="/admin/edit_book/<?=$book->getId()?>">Edit</a></td>
            </tr>
                <?php endif;?>
            <?php endforeach; ?>
        </tbody>
    </table>
</section>
<div id="dvCSV">
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

<script type="text/javascript">
    $(function () {
        $("#upload").bind("click", function () {
            var regex = /^([a-zA-Z0-9\s_\\.\-:])+(.csv|.txt)$/;
            if (regex.test($("#fileUpload").val().toLowerCase())) {
                if (typeof (FileReader) != "undefined") {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        var table = $("<table />");
                        var rows = e.target.result.split("\n");
                        for (var i = 0; i < rows.length; i++) {
                            var row = $("<tr />");
                            var cells = rows[i].split(",");
                            if (cells.length > 1) {
                                for (var j = 0; j < cells.length; j++) {
                                    var cell = $("<td />");
                                    cell.html(cells[j]);
                                    row.append(cell);
                                }
                                table.append(row);
                            }
                        }
                        $("#dvCSV").html('');
                        $("#dvCSV").append(table);
                    }
                    reader.readAsText($("#fileUpload")[0].files[0]);
                } else {
                    alert("This browser does not support HTML5.");
                }
            } else {
                alert("Please upload a valid CSV file.");
            }
        });
    });
</script>
<?php require_once(__DIR__ . '/../../common/footer.phtml'); ?>

